In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 1 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [2]:
#=================================================-
#### Slide 7: Creating arrays  ####

# Import numpy as 'np' sets 'np' as the shortcut/alias.
import numpy as np

# Create an array from a list. 
arr = np.array([17, -10, 16.8, 11])
print(arr)

# Check the type of the object.
print(type(arr))


[ 17.  -10.   16.8  11. ]
<class 'numpy.ndarray'>


In [3]:
#=================================================-
#### Slide 8: Data type in arrays  ####

# Check the data type stored in the array.
print(arr.dtype)


float64


In [ ]:
#=================================================-
#### Slide 9: Using ndarray  ####

x = np.array([3, 19, 7, 11])
print(x)




In [ ]:
#=================================================-
#### Slide 11: Building an array with linspace  ####

y = np.linspace(-2, -1, 25)
print(y)




In [1]:
#=================================================-
#### Slide 12: Alternative ways of accessing functions  ####

from numpy import array, linspace
x = array([0.01, 0.45, -0.3])
y = linspace(0, 1, 50)

print(x)
print(y)


[ 0.01  0.45 -0.3 ]
[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [ ]:
#=================================================-
#### Slide 16: Arrays vs. lists  ####

mixed_array = np.array([1, 2, "apple", "XYZ", 5.5])
print(mixed_array)




In [ ]:
#=================================================-
#### Slide 17: Arrays vs lists (cont'd)  ####

print(mixed_array.dtype)
mixed_array = np.array([3, 12, 5.56])
print(mixed_array)
print(mixed_array.dtype)




In [ ]:
#=================================================-
#### Slide 19: Arrays from sequences (cont'd)  ####

rng = np.arange(0, 51)
print(rng)




In [ ]:
#=================================================-
#### Slide 20: Arrays from sequences - using a step size  ####

evens = np.arange(0, 23, 2)
print(evens)

quarters = np.arange(0, 1, .25)  #<- contains 0 to 0.75
print(quarters)


#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################


In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 2 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [3]:
#=================================================-
#### Slide 2: Helper functions: min and max  ####

import numpy as np

# Generate 5 numbers between 15 and 19.
x = np.linspace(15, 19, 5)

# Find the min of x.
print(np.amin(x))
# Find the max of x.
print(np.amax(x))




15.0
19.0


In [4]:
#=================================================-
#### Slide 3: Helper functions: argmin and argmax  ####

# Obtain index of max value
np.argmax(x)
# Obtain index of min value
np.argmin(x)




0

In [ ]:
#=================================================-
#### Slide 4: Helper functions: sum  ####

# Find the max of x.
np.sum(x)




In [ ]:
#=================================================-
#### Slide 5: Helper functions: mean and median  ####

# Find the mean of x.
np.mean(x)
# Find the median of x.
np.median(x)




In [12]:
#=================================================-
#### Slide 6: Helper functions: digitize  ####

# Filter array using digitize
bins = np.array([15, 17])
print(bins)
print(x)
np.digitize(x,bins)
# print(np.digitize(x,bins))
# print(np.digitize(x,bins,right=True))





[15 17]
[15. 16. 17. 18. 19.]


array([1, 1, 2, 2, 2])

In [19]:
#=================================================-
#### Slide 7: Helper functions: expand and squeeze  ####

print(x)
# Expand dimensions of the array horizontally
np.expand_dims(x,axis=0)


[15. 16. 17. 18. 19.]


array([[15., 16., 17., 18., 19.]])

In [21]:
# Expand dimensions of the array vertically
np.expand_dims(x,axis=1)


array([[15.],
       [16.],
       [17.],
       [18.],
       [19.]])

In [22]:
np.expand_dims(x,axis=1).squeeze()

array([15., 16., 17., 18., 19.])

In [23]:
#=================================================-
#### Slide 8: Helper functions: expand and squeeze (cont'd)  ####

# Define an array in the format of lists
y = np.array([[10],[25],[28],[30]])
# Reduce dimensions of the array
np.squeeze(y)




array([10, 25, 28, 30])

In [24]:
#=================================================-
#### Slide 9: Convert an array to a list  ####

evens = np.arange(0, 23, 2)
# this is an array
print(evens)
# this is a list
print(list(evens))




[ 0  2  4  6  8 10 12 14 16 18 20 22]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]


In [25]:
#=================================================-
#### Slide 10: Operations on arrays  ####

# Save two arrays as variables.
a = np.array([1,1,1,1])
b = np.array([2,2,2,2])

# Addition of arrays.
print(a + b)

# Subtraction of arrays.
print(a - b)
# Multiplication of arrays.
print(a * b)
# Division of arrays.
print(a / b)




[3 3 3 3]
[-1 -1 -1 -1]
[2 2 2 2]
[0.5 0.5 0.5 0.5]


In [33]:
#=================================================-
#### Slide 12: Set operations  ####
print(a)
b = np.array([2,2,2,2])
print(b)
c = np.array([1,2,3,4])
# Retrieving common elements present in the arrays.
np.intersect1d(a, b, return_indices=True)
np.intersect1d(a, b, return_indices=False)


[1 1 1 1]
[2 2 2 2]


array([], dtype=int64)

In [36]:
print(b)
print(c)
np.intersect1d(b,c,return_indices=True)

[2 2 2 2]
[1 2 3 4]


(array([2]), array([0]), array([1]))

In [27]:
# Retrieving elements present in both the arrays.
np.union1d(a, b)


array([1, 2])

In [28]:
# Retrives the elements that are present only in the first array.
# i.e., element in a, not b
np.setdiff1d(a, b)


array([1])

In [ ]:
#=================================================-
#### Slide 13: Stacking arrays  ####

# Stacking arrays horizontally.
np.hstack((a,b))

# Stacking arrays vertically.
np.vstack((a,b))




In [37]:
#=================================================-
#### Slide 15: Mathematical functions on arrays  ####

print(np.abs(-3))
print(np.abs([-2, -7, 1]))
nums = np.arange(20, 30, .5)
print(len(nums))




3
[2 7 1]
20


In [ ]:
#=================================================-
#### Slide 16: User-defined functions on arrays  ####

# Define a function to multiply every element in array with 3 and add 1
def some_calculation(arr):
    return 3*arr+1
    
print(some_calculation(nums))


#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################


In [39]:
A = np.random.rand(4, 1, 2)  # Shape (4, 1, 2)
B = np.random.rand(1, 3, 1)  # Shape (1, 3, 1)
print(A)
print(B)
C = A + B  # Example of element-wise addition
print(C.shape)  # This will print (4, 3, 2)

[[[0.37420586 0.86757032]]

 [[0.53859243 0.48416962]]

 [[0.35875625 0.22862644]]

 [[0.57489307 0.27697518]]]
[[[0.54425296]
  [0.64752173]
  [0.81550708]]]
(4, 3, 2)


In [ ]:
#######################################################
#######################################################
############    COPYRIGHT - DATA SOCIETY   ############
#######################################################
#######################################################

## DATAWRANGLINGINPYTHON/DATAWRANGLINGWITHNUMPY/DATAWRANGLINGINPYTHON DATAWRANGLINGWITHNUMPY 3 ##

## NOTE: To run individual pieces of code, select the line of code and
##       press ctrl + enter for PCs or command + enter for Macs




In [ ]:
#=================================================-
#### Slide 2: Recap: arrays  ####

# Import numpy as 'np' sets 'np' as the shortcut/alias.
import numpy as np




In [ ]:
#=================================================-
#### Slide 3: Accessing array values  ####

nums = np.arange(20, 30, .5)

print(nums[1])  #<- get the second element

print(nums[0:3]) #<- get the first three elements




In [ ]:
#=================================================-
#### Slide 4: Logical filtering  ####

print(nums)

large_nums = nums[nums > 26]
print(large_nums)




In [ ]:
#=================================================-
#### Slide 5: Logical filtering (cont'd)  ####

print(nums)

large_nums = nums[nums > 26]
print(large_nums)




In [40]:
#=================================================-
#### Slide 6: Two-dimensional arrays  ####

mat = np.array([
        [8, 2, 6, 8],
        [4, 5, 7, 2],
        [3, 9, 7, 1]
       ])
print(mat)




[[8 2 6 8]
 [4 5 7 2]
 [3 9 7 1]]


In [41]:
#=================================================-
#### Slide 8: Two-dimensional arrays - shape (cont'd)  ####

print(mat.shape) #<- 3 rows and 4 columns -- returned as a tuple
nrows, ncols = mat.shape
print(nrows)




(3, 4)
3


In [ ]:
#=================================================-
#### Slide 9: Two-dimensional arrays - extracting elements  ####

print(mat[1, 3]) #<- 2nd row 4th column - remember that indexing starts at 0!




In [ ]:
#=================================================-
#### Slide 10: Two-dimensional arrays - rows  ####

print(mat[0, :]) #<- first row
print(mat[0, 0:2]) #<- first row and just first 2 columns




In [ ]:
#=================================================-
#### Slide 11: Two-dimensional arrays - columns  ####

print(mat[:, 2]) #<- 3rd column
print(mat[1:3, 2]) #<- 3rd column but skipping over the first row
print(mat[1:3, 2:3]) #<- same as previous, but maintains the vertical structure of the column




In [ ]:
#=================================================-
#### Slide 13: Reshaping arrays  ####

arr = np.arange(1,13)
print(arr)
print(arr.reshape(3, 4))




In [ ]:
#=================================================-
#### Slide 15: Reshaping arrays (cont'd)  ####

print(arr.reshape(2,      #<- specify number of rows=2
                  2))     #<- number of columns=2 throws error




In [ ]:
#=================================================-
#### Slide 17: Exercise   ####




#######################################################
####  CONGRATULATIONS ON COMPLETING THIS MODULE!   ####
#######################################################
